import { Apps } from "./app-interface";

export const APPS: Apps[] = [
  {
     "downloadUrl":"https://github.com/2sic/app-accordion/releases/download/v04.02.01/2sxcApp_Accordion_4.2.1.zip",
     "displayName":"Accordion v4",
     "gitHub":"https://github.com/2sic/app-accordion",
     "icon":"/Portals/0/adam/AppCatalog/rDZec0nRx0iYUTVRlkfTJQ/Icon/app-Icon.png",
     "urlKey":"accordion-v4-hybrid-for-dnn-and-oqtane",
     "shortDescription":"This accordion shows headers which slide to reveal more content. Fully configurable, CSS optimized for bootstrap 4.",
     "version":"04.02.01",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-blog/releases/download/v05.02.00/2sxcApp_Blog_5.2.0.zip",
     "displayName":"Blog v5",
     "gitHub":"https://github.com/2sic/app-blog",
     "icon":"/Portals/0/adam/AppCatalog/gDuy2MKMUESBsY-EG7G8NQ/Icon/app-icon.png",
     "urlKey":"blog-v5-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A simple, elegant blog app with all the basics. Use right away or adapt to turn it into anything you want.",
     "version":"05.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-counter/releases/download/v02.02.00/2sxcApp_Counter_2.2.0.zip",
     "displayName":"Counter v2",
     "gitHub":"https://github.com/2sic/app-counter",
     "icon":"/Portals/0/adam/AppCatalog/Q01F_14-Nke9B3De-NvQ0Q/Icon/app-icon.png",
     "urlKey":"counter2-hybrid-for-dnn-and-oqtane",
     "shortDescription":"Counter to show facts in a dynamic way.",
     "version":"02.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-faq/releases/download/v04.02.00/2sxcApp_FAQQuestionsAnswers_4.2.0.zip",
     "displayName":"FAQ v4",
     "gitHub":"https://github.com/2sic/app-faq",
     "icon":"/Portals/0/adam/AppCatalog/0Asb7rOYVU21JCH28GlpZQ/Icon/app-icon.png",
     "urlKey":"faq4-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A simple but very powerful FAQ App.",
     "version":"04.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-glossary/releases/download/v03.02.00/2sxcApp_Glossary_3.2.0.zip",
     "displayName":"Glossary v3",
     "gitHub":"https://github.com/2sic/app-glossary",
     "icon":"/Portals/0/adam/AppCatalog/ascfZug8d0W4YDM3sIZ3YA/Icon/app-icon.png",
     "urlKey":"glossary3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A glossary App with A-Z bar, terms ordered by A-Z, short description and details page.",
     "version":"03.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-iframe/releases/download/v03.01.00/2sxcApp_IFrame_3.1.0.zip",
     "displayName":"IFrame v3",
     "gitHub":"https://github.com/2sic/app-iframe",
     "icon":"/Portals/0/adam/AppCatalog/nR6IgnbOJESXZjWId0QC0w/Icon/app-icon.png",
     "urlKey":"iframe3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A simple IFrame app for embedding other websites on your own.",
     "version":"03.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-gallery/releases/download/v07.02.00/2sxcApp_ImageGallery_7.2.0.zip",
     "displayName":"Gallery App v7 using Fancybox 4 (Hybrid - for Dnn and Oqtane) ",
     "gitHub":"https://github.com/2sic/app-gallery-fancybox3",
     "icon":"/Portals/0/adam/AppCatalog/XiBUt1zMG06kK9pQQa8wZg/Icon/app-icon.png",
     "urlKey":"gallery-app-v7-using-fancybox-4-hybrid-for-dnn-and-oqtane",
     "shortDescription":"Create Albums with a few clicks and add images easily via drag & drop.",
     "version":"07.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-image-compare/releases/download/v02.01.00/2sxcApp_ImageCompare_2.1.0.zip",
     "displayName":"Compare Images v2 (before/after)",
     "gitHub":"https://github.com/2sic/app-image-compare",
     "icon":"/Portals/0/adam/AppCatalog/ThcxyBnVbUKuG_4Do8H7lQ/Icon/app-icon.png",
     "urlKey":"compare-images-v2-using-beerslider-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A nice simple app which shows two images overlaid with a split-bar that can be moved by mouse or hand. ",
     "version":"02.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-image-hotspots/releases/download/v03.01.00/2sxcApp_ImageHotspots_3.1.0.zip",
     "displayName":"Image Hotspots App v3 (Hybrid for Dnn / Oqtane)",
     "gitHub":"https://github.com/2sic/app-image-hotspots",
     "icon":"/Portals/0/adam/AppCatalog/vk-F_Z0syUeEZmyiGysGaQ/Icon/app-icon.png",
     "urlKey":"image-hotspots-v3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"App for putting Hotspots on Image",
     "version":"03.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-employees-directory/releases/download/v04.02.00/2sxcApp_PeopleDirectory_4.2.0.zip",
     "displayName":"People Directory v4",
     "gitHub":"https://github.com/2sic/app-employees-directory",
     "icon":"/Portals/0/adam/AppCatalog/DJ7gy3lPzkSzftm8auYlyA/Icon/app-icon.png",
     "urlKey":"people-directory-v4-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A simple, elegant People Directory. It also demonstrates how to create powerful token based Apps. ",
     "version":"04.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-podcast/releases/download/v02.02.00/2sxcApp_PodCast_2.2.0.zip",
     "displayName":"Podcast v2",
     "gitHub":"https://github.com/2sic/app-podcast",
     "icon":"/Portals/0/adam/AppCatalog/M8-cP6SDdkqukovZkx1FIw/Icon/app-icon.png",
     "urlKey":"podcast-v2-hybrid-for-dnn-and-oqtane",
     "shortDescription":"Create a podcast, add episodes and publish it on spotify and iTunes with a few steps.",
     "version":"02.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-popup/releases/download/v03.02.00/2sxcApp_Pop-UpMessage_3.2.0.zip",
     "displayName":"Popup Message v3",
     "gitHub":"https://github.com/2sic/app-popup",
     "icon":"/Portals/0/adam/AppCatalog/nPpdqsQgIEWSqDFtx0hK6g/Icon/app-icon.png",
     "urlKey":"popup-v3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A Popup App with various display settings.",
     "version":"03.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-qr/releases/download/v02.01.00/2sxcApp_QRCode_2.1.0.zip",
     "displayName":"QR Code v2",
     "gitHub":"https://github.com/2sic/app-qr",
     "icon":"/Portals/0/adam/AppCatalog/WfMb5GljLkODlyK6Cj4Fxg/Icon/app-icon.png",
     "urlKey":"qr-code-v2-hybrid-for-dnn-and-oqtane",
     "shortDescription":"Create a QR Code for any link you want or for the current page. ",
     "version":"02.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-snippet-inject/releases/download/v03.01.00/2sxcApp_SnippetInjectHTMLCSSJS_3.1.0.zip",
     "displayName":"Snippet Inject v3",
     "gitHub":"https://github.com/2sic/app-snippet-inject",
     "icon":"/Portals/0/adam/AppCatalog/eEcgPSJYk0uLmnifFYBQPg/Icon/app-icon.png",
     "urlKey":"snippet-inject-v3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"Quickly inject any js / css / html to your page",
     "version":"03.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-swiper/releases/download/v02.04.00/2sxcApp_SwiperSlider_2.4.0.zip",
     "displayName":"Swiper - Image-Slider Pro v2 with Parallax, 3D Cubes, CoverFlow and more (Hybrid Dnn/Oqtane) ",
     "gitHub":"https://github.com/2sic/app-swiper",
     "icon":"/Portals/0/adam/AppCatalog/-ZwSeUXuW0iuKS7DpRRLpA/Icon/app-icon.png",
     "urlKey":"swiper-image-slider-pro-v2-with-parallax-3d-cubes-coverflow-and-more-hybrid-for-dnn-and-oqtane",
     "shortDescription":"An awesome slider / carousel based on SwiperJs",
     "version":"02.04.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-mobius-forms/releases/download/v05.04.00/2sxcApp_MobiusForms_5.4.0.zip",
     "displayName":"Mobius Forms v5 with Mailchimp, Recaptcha and more",
     "gitHub":"https://github.com/2sic/app-mobius-forms",
     "icon":"/Portals/0/adam/AppCatalog/-hRbbdh7Dk6Ahf3K_qy5KQ/Icon/app-icon.png",
     "urlKey":"mobius-forms-v5-with-mailchimp-recaptcha-polymorph-weback-and-more-hybrid-for-dnn-and-oqtane",
     "shortDescription":"Mobius Forms is a online form, which can be customized to be everything.",
     "version":"05.04.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/cta-app/releases/download/v03.02.00/2sxcApp_CallToAction_3.2.0.zip",
     "displayName":"CTA v3",
     "gitHub":"https://github.com/2sic/cta-app",
     "icon":"/Portals/0/adam/AppCatalog/YUqXTjO9Z0CxNgv8nFJD9A/Icon/app-icon.png",
     "urlKey":"cta-v3-for-dnn-and-oqtane",
     "shortDescription":"This call to action app shows beatiful predesigned sections with action buttons.",
     "version":"03.02.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-news/releases/download/v05.01.00/2sxcApp_News_5.1.0.zip",
     "displayName":"News for 2sxc v5",
     "gitHub":"https://github.com/2sic/app-news",
     "icon":"/Portals/0/adam/AppCatalog/GsbARYZ0i02Tm2qRl_Q5kg/Icon/app-icon.png",
     "urlKey":"news-app-v5-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A powerful news app with all the features you expect and more, for bootstrap 3 and 4.",
     "version":"05.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-add-search/releases/download/v03.01.00/2sxcApp_AddSearch_3.1.0.zip",
     "displayName":"AddSearch v3",
     "gitHub":"https://github.com/2sic/app-add-search",
     "icon":"/Portals/0/adam/AppCatalog/qzV3ducIFUesODIDgh6Akw/Icon/app-icon.png",
     "urlKey":"addsearch-app-v3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A Search App to enable search functionality over you entire website.",
     "version":"03.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/App-Disqus/releases/download/v03.01.00/2sxcApp_disqus_3.1.0.zip",
     "displayName":"disqus v3 for DNN",
     "gitHub":"https://github.com/2sic/App-Disqus",
     "icon":"/Portals/0/adam/AppCatalog/yrvVTHANV0WqwQjD4C9K9g/Icon/app-icon.png",
     "urlKey":"disqus-app-v3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"Integrate disqus with DNN within minutes to give your pages a facebook/blog style feedback discussion feature.",
     "version":"03.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-jobs/releases/download/v02.01.00/2sxcApp_Jobs_2.1.0.zip",
     "displayName":"Jobs v2",
     "gitHub":"https://github.com/2sic/app-jobs",
     "icon":"/Portals/0/adam/AppCatalog/U6AQ-QOYXkeqs95E-m-qRg/Icon/app-icon.png",
     "urlKey":"jobs-app-v2-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A powerful app to list job offerings and more, for bootstrap 3, 4 and 5.",
     "version":"02.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-timelinejs/releases/download/v02.01.00/2sxcApp_TimelineJS_2.1.0.zip",
     "displayName":"TimelineJS v2",
     "gitHub":"https://github.com/2sic/app-timelinejs",
     "icon":"/Portals/0/adam/AppCatalog/5V8XATpQ_Ee9LmKSTicf9Q/Icon/app-icon.png",
     "urlKey":"timelinejs-app-v2-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A DNN Implementation of the amazing TimelineJS",
     "version":"02.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  },
  {
     "downloadUrl":"https://github.com/2sic/app-timeline/releases/download/v03.01.00/2sxcApp_Timeline_3.1.0.zip",
     "displayName":"Timeline v3",
     "gitHub":"https://github.com/2sic/app-timeline",
     "icon":"/Portals/0/adam/AppCatalog/gY4HmqiD00CXbw-c_nGliA/Icon/app-icon.png",
     "urlKey":"timeline-app-v3-hybrid-for-dnn-and-oqtane",
     "shortDescription":"A powerful timeline app with all the features you expect and more, for bootstrap 4 and 5.",
     "version":"03.01.00",
     "minDnn":"07.04.02",
     "min2Sxc":"13.10.00",
     "minOqt":"03.01.00"
  }
]
